<?php

/**
 * @file
 * Convert output of date_format() to Jalali in a patched drupal installation.
 *
 */

/**
 * Implements hook_help().
 */
function datex_help($path, $arg) {
  if ($path == 'admin/help#datex') {
    $output = '<p>';
    $output .= t('By enabling Datex, Gregorian dates generates by drupal function %func will be converted to it\'s Jalali equivilant.', array('%type' => 'date_format()'));
    $output .= '</p><p>';
    $output .= t('Note that this module requires drupal file %file to be patched', array('%file' => 'common.inc'));
    $output .= t('The patch resides in Datex module folder');
    $output .= '</p>';
    return $output;
  }
}

/**
 * Implements hook_datex_format_alter().
 * 
 */
function datex_datex_format_alter(&$data, &$context) {
  if ($context[4] == 'fa') {
    $data = DatexFormatter::format(intval($context[0]), $context[2]);
  }
}
