<?php

/**
 * Implements hook_libraries_info().
 *
 */
function datex_jquery_libraries_info() {
  $libraries = array();

  $libraries['jquery.calendars'] = array(
    'name' => 'jQuery Calendars',
    'vendor url' => 'http://keith-wood.name/',
    'download url' => 'http://keith-wood.name/calendars.html',
    'version arguments' => array(
      'file' => 'jquery.calendars.pack.js',
      'pattern' => '/Calendars for jQuery v(\d.\d.\d)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array('jquery.calendars.pack.js'),
      'css' => array(
        'ui.calendars.picker.css',
        'ui-mint-choc.calendars.picker.css'
        ),
    ),
  );

  $libraries['jquery.datepicker'] = array(
    'name' => 'jQuery Datepicker',
    'vendor url' => 'http://keith-wood.name/',
    'download url' => 'http://keith-wood.name/datepick.html',
    'version arguments' => array(
      'file' => 'jquery.datepick.pack.js',
      'pattern' => '/Date picker for jQuery v(\d.\d.\d)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array('jquery.datepick.pack.js'),
      'css' => array(
        'ui.datepick.css',
        'jquery.datepick.css',
        ),
    ),
    'dependencies' => array(
      'jquery.calendars'
    ),
  );

  $libraries['jquery.datepicker.fa'] = array(
    'name' => ' jQuery Datepicker Persian',
    'vendor url' => 'http://keith-wood.name/',
    'download url' => 'http://keith-wood.name/calendars.html',
    'version callback' => 'datex_jquery_intl_version_callback',
    'files' => array(
      'js' => array('jquery.datepicker.fa.js'),
    ),
    'dependencies' => array(
      'query.datepicker'
    ),
  );

  $libraries['jquery.dateentry'] = array(
    'name' => 'jQuery Date Entry',
    'vendor url' => 'http://keith-wood.name/',
    'download url' => 'http://keith-wood.name/dateEntry.html',
    'version arguments' => array(
      'file' => 'jquery.dateentry.pack.js',
      'pattern' => '/Date entry for jQuery v(\d.\d.\d.)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array('jquery.dateentry.pack.js'),
      'css' => array('jquery.dateentry.css'),
    ),
  );

  $libraries['jquery.datepicker.fa'] = array(
    'name' => ' jQuery Datepicker Persian',
    'vendor url' => 'http://keith-wood.name/',
    'download url' => 'http://keith-wood.name/calendars.html',
    'version callback' => 'datex_jquery_intl_version_callback',
    'files' => array(
      'js' => array('jquery.datepicker.fa.js'),
    ),
    'dependencies' => array(
      'jquery.datepicker'
    ),
  );

  $libraries['jquery.timeentry'] = array(
    'name' => ' jQuery Time Entry',
    'vendor url' => 'http://keith-wood.name/',
    'download url' => 'http://keith-wood.name/timeEntry.html',
    'version arguments' => array(
      'file' => 'jquery.timeentry.pack.js',
      'pattern' => '/ Time entry for jQuery v(\d.\d.\d.)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array('jquery.timeentry.pack.js'),
      'css' => array('jquery.timeentry.css'),
    ),
  );

  $libraries['jquery.timeentry.fa'] = array(
    'name' => ' jQuery DateTime Entry Persian',
    'vendor url' => 'http://keith-wood.name/',
    'download url' => 'http://keith-wood.name/calendars.html',
    'version callback' => 'datex_jquery_intl_version_callback',
    'files' => array(
      'js' => array('jquery.timeentry.fa.js'),
    ),
    'dependencies' => array(
      'jquery.datetimeentry'
    ),
  );

  $libraries['jquery.datetimeentry'] = array(
    'name' => ' jQuery DateTime Entry',
    'vendor url' => 'http://keith-wood.name/',
    'download url' => 'http://keith-wood.name/datetimeEntry.html',
    'version arguments' => array(
      'file' => 'jquery.datetimeentry.min.js',
      'pattern' => '/Date and time entry for jQuery v(\d.\d.\d.)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array('jquery.datetimeentry.min.js'),
      'css' => array('jquery.datetimeentry.css'),
    ),
  );

  $libraries['jquery.datetimeentry.fa'] = array(
    'name' => ' jQuery DateTime Entry Persian',
    'vendor url' => 'http://keith-wood.name/',
    'download url' => 'http://keith-wood.name/calendars.html',
    'version callback' => 'datex_jquery_intl_version_callback',
    'files' => array(
      'js' => array('jquery.datetimeentry.fa.js'),
    ),
    'dependencies' => array(
      'jquery.datetimeentry'
    ),
  );

  return $libraries;
}

/**
 * Required by datex_popup_libraries_info().
 * @return int
 */
function datex_jquery_intl_version_callback() {
  //intl file has no version.
  return 1;
}

/**
 * Loads requested js libraries.
 *
 * @param type $libraries
 */
function datex_jquery_add_libraries($libraries = NULL, $intl = NULL) {
  //required for all.
  libraries_load('jquery.calendars');

  if (is_array($libraries)) {
    unset($libraries['jquery.calendars']);
    foreach ($libraries as $library) {
      libraries_load($library);
      if ($intl) {
        libraries_load($library . ".$intl");
      }
    }
  }
  elseif (is_string($libraries)) {
    libraries_load($libraries);
    if ($intl) {
      libraries_load($libraries . ".$intl");
    }
  }
}
