<?php

/**
 * Implements hook_help().
 */
function datex_date_help($path, $arg) {
  if ($path == 'admin/help#datex_date') {
    $output = '<p>';
    $output .= t('By enabling Datex Date, Gregorian dates generates by');
    $output .= t('<em> Date module </em>');
    $output .= t('will be displayed in Jalali format.');
    $output .= '<br/>';
    $output .= t('When storing date fields, they will be converted back to Gregorian format');
    $output .= t('to prevent problems caused by databases not supporting dates other than Gregorian,');
    $output .= '</p><p>';
    $output .= t('Please be noted that Datex Date will not change display of dates when UI language is not Persian.');
    $output .= '</p>';
    return $output;
  }
}

/**
 * Implemetns hook_date_formatter_dates_alter().
 *
 * Converts gregorian date to Jalali date before display (as in node view).
 */
function datex_date_date_formatter_dates_alter(&$dates, $context) {
  global $language;
  if ($language->language == 'fa') {
    $cache = cache_get('dx-' . $dates['value']['formatted_iso']);
    if (empty($cache->data)) {
      $cache = DatexFormatter::format(strtotime($dates['value']['formatted_iso']), $context['format'],  variable_get('datex_api_intl', 0));
      cache_set('dx-' . $dates['value']['formatted_iso'], $cache);
      $dates['value']['formatted'] = $cache;
    }
    else {
      $dates['value']['formatted'] = $cache->data;
    }

    $cache = cache_get('dx-' . $dates['value2']['formatted_iso']);
    if (empty($cache->data)) {
      $cache = DatexFormatter::format(strtotime($dates['value2']['formatted_iso']), $context['format'], variable_get('datex_api_intl', 0));
      cache_set('dx' . $dates['value2']['formatted_iso'], $cache);
      $dates['value2']['formatted'] = $cache;
    }
    else {
      $dates['value2']['formatted'] = $cache->data;
    }
  }
}

/**
 * Implements hook date_select_process_alter().
 *
 * Converts Gregorian date to Jalali date before displaying it in Form API.
 * (such as node edit form).
 */
function datex_date_date_select_process_alter(&$element, &$form_state, $context) {
  global $language;
  if ($language->language == 'fa') {
    $persian_date_names = DatexFormatter::persianDateNames();

    $default = DatexFormatter::toJalali(
            @$element['year']['#default_value'], @$element['month']['#default_value'], @$element['day']['#default_value']
    );

    if (in_array('year', $element['#granularity']) && array_key_exists('#default_value', $element['year'])) {
      $element['year']['#default_value'] = $default['year'];
    }
    if (in_array('month', $element['#granularity']) && array_key_exists('#default_value', $element['month'])) {
      $element['month']['#default_value'] = $default['month'];
    }
    if (in_array('day', $element['#granularity']) && array_key_exists('#default_value', $element['day'])) {
      $element['day']['#default_value'] = $default['day'];
    }

    //Generating Year Option (if field has year granularity):
    if (in_array('year', $element['#granularity'])) {
      //get year range
      list($year_before, $year_after) = explode(':', $element['#date_year_range']);
      $year_before = intval($year_before);
      $year_after = intval($year_after);

      $element['year']['#options'] = array();

      //if year field is not required, add an empty value as drupal does.
      if (!$element['#required']) {
        $element['year']['#options'][''] = '';
      }

      //now add actual year options
      $year_now = DatexFormatter::getYear();
      for ($year = $year_now + $year_before; $year <= $year_now + $year_after; $year++) {
        $element['year']['#options'][$year] = $year;
      }
    }

    //Generating month Option (if field has month granularity).
    if (in_array('month', $element['#granularity'])) {
      $element['month']['#options'] = array();

      //if field is not required, add an empty value as drupal does.
      if (!$element['#required']) {
        $element['month']['#options'][''] = '';
      }

      //now add month options
      for ($i = 1; $i < 13; $i++) {
        $element['month']['#options'][$i] = $persian_date_names['months'][$i];
      }
    }

    //we don't need to change day options, in a date field input (select mode)
    //day is alwys from 1 to 31, and also validation will happen later.
  }
}

/**
 * Implements hook_date_date_select_pre_validate_alter().
 *
 * Converts Jalali date to Gregorian date before storing it in database (such
 * as node edit form submit).
 * Works for Date module's Select widget.
 */
function datex_date_date_select_pre_validate_alter(&$element, &$form_state, &$input) {
  global $language;
  if ($language->language == 'fa') {
    dargs();
    $field_name = $element['#instance']['field_name'];
    $delta = $element['#delta'];
    $dates = DatexFormatter::toGregorian(
        @$form_state['input'][$element['#array_parents'][0]][$element['#array_parents'][1]][$element['#array_parents'][2]][$element['#array_parents'][3]]['year'],
        @$form_state['input'][$element['#array_parents'][0]][$element['#array_parents'][1]][$element['#array_parents'][2]][$element['#array_parents'][3]]['month'],
            @$form_state['input'][$element['#array_parents'][0]][$element['#array_parents'][1]][$element['#array_parents'][2]][$element['#array_parents'][3]]['day']
    );

    $form_state['input'][$element['#array_parents'][0]][$element['#array_parents'][1]][$element['#array_parents'][2]][$element['#array_parents'][3]]['year'] = $dates['year'];
    $form_state['input'][$element['#array_parents'][0]][$element['#array_parents'][1]][$element['#array_parents'][2]][$element['#array_parents'][3]]['month'] = $dates['month'];
    $form_state['input'][$element['#array_parents'][0]][$element['#array_parents'][1]][$element['#array_parents'][2]][$element['#array_parents'][3]]['day'] = $dates['day'];
  }
}

function datex_date_date_field_instance_settings_form_alter(&$form, $context) {
  dargs();
}

//function datex_date_date_select_pre_validate_alter(&$element, &$form_state, &$input) {
//  dargs();
//  global $language;
//  if ($language->language == 'fa') {
//    $dates = DatexFormatter::toGregorian($input['year'], $input['month'], $input['day']);
//    list($year,$month,$day) = array($dates['year'], $dates['month'], $dates['day']);
//
//    $granularities = $element['#granularity'];
//    $input['year'] = isset($granularities['year']) ? $year : 0;
//    $input['month'] = isset($granularities['month']) ? $month : 0;
//    $input['day'] = isset($granularities['day']) ? $day : 0;
//    dargs();
//  }
//}
